import {
  generateInterfaceDefinition,
  generateSvgConstant,
  generateTypeDefinition,
  generateVariableName
} from './code-snippet-generators';
import { MultiFileConvertionOptions, SingleFileConvertionOptions } from '../options/convertion-options';
import { SvgDefinition } from '../converters/shared.converter';

describe('Generators', () => {
  describe('generateInterfaceDefinition', () => {
    it('should return the correct interface definition when passing generateType', () => {
      const options = {
        generateType: true,
        typeName: 'AppIcons',
        interfaceName: 'IconInterface'
      } as SingleFileConvertionOptions;
      const expected = `export interface ${options.interfaceName}{
        name: ${options.typeName};
        data: string;}`;
      expect(generateInterfaceDefinition(options)).toEqual(expected);
    });

    it('should return the correct interface definition when passing generateTypeObject', () => {
      const options = {
        generateTypeObject: true,
        typeName: 'AppIcons',
        interfaceName: 'IconInterface'
      } as SingleFileConvertionOptions;
      const expected = `export interface ${options.interfaceName}{
        name: string;
        data: string;}`;
      expect(generateInterfaceDefinition(options)).toEqual(expected);
    });

    it('should return the correct interface definition when not generating a type', () => {
      const options = { typeName: 'AppIcons', interfaceName: 'IconInterface' } as SingleFileConvertionOptions;
      const expected = `export interface ${options.interfaceName}{
        name: string;
        data: string;}`;
      expect(generateInterfaceDefinition(options)).toEqual(expected);
    });
  });

  describe('generateTypeDefinition', () => {
    let expected;
    beforeEach(() => {
      expected = `
    /* ⚠️ Do not edit this file - this file is generated by svg-to-ts*/
    
  `;
    });
    it('should only print the warning', () => {
      const options = {} as SingleFileConvertionOptions;
      expect(generateTypeDefinition(options, [])).toEqual(expected);
    });

    it('should create type definition', () => {
      const options = { generateType: true, typeName: 'AppIcons' } as SingleFileConvertionOptions;
      const types = ['alert', 'noResults'];
      const svgDefinitions = types.map(typeName => ({ typeName })) as SvgDefinition[];
      expected += `
    export type ${options.typeName} = ${types.map(v => `'${v}'`).join(' | ')};`;
      expect(generateTypeDefinition(options, svgDefinitions)).toEqual(expected);
    });

    it('should create type definition object', () => {
      const options = { generateTypeObject: true, typeName: 'AppIcons' } as SingleFileConvertionOptions;
      const types = ['alert', 'noResults'];
      const svgDefinitions = types.map(typeName => ({ typeName })) as SvgDefinition[];
      expected += `
    export const ${options.typeName} = {
      ${types.map(v => `${v}: '${v}'`).join(',')}
    };`;
      expect(generateTypeDefinition(options, svgDefinitions)).toEqual(expected);
    });

    it('should create both type definitions', () => {
      const options = {
        generateType: true,
        generateTypeObject: true,
        typeName: 'AppIcons'
      } as SingleFileConvertionOptions;
      const types = ['alert', 'noResults'];
      const svgDefinitions = types.map(typeName => ({ typeName })) as SvgDefinition[];
      expected += `
    export type ${options.typeName} = ${types.map(v => `'${v}'`).join(' | ')};`;
      expected += `
    export const ${options.typeName} = {
      ${types.map(v => `${v}: '${v}' as ${options.typeName}`).join(',')}
    };`;
      expect(generateTypeDefinition(options, svgDefinitions)).toEqual(expected);
    });
  });

  it('should return the correct svg constant definition', () => {
    const variableName = 'smile';
    const filenameWithoutEnding = 'smileFile';
    const data = 'some data';
    const interfaceName = 'AwesomeIcon';

    const expectedSVGConstant = `export const ${variableName}: ${interfaceName} = {
                name: '${filenameWithoutEnding}',
                data: \`${data}\`
            };`;
    expect(generateSvgConstant(variableName, interfaceName, filenameWithoutEnding, data)).toEqual(expectedSVGConstant);
  });

  describe('generateVariableName', () => {
    it('should return the correct variable name', () => {
      const prefix = '';
      const fileName = 'alert';
      const expectedVariable = `alert`;
      expect(generateVariableName(prefix, fileName)).toEqual(expectedVariable);
    });

    it('should return the correct variable name - no prefix', () => {
      const prefix = 'myIcon';
      const fileName = 'alert';
      const expectedVariable = `myIconAlert`;
      expect(generateVariableName(prefix, fileName)).toEqual(expectedVariable);
    });
  });
});
