import fs from 'fs';
import gfs from 'graceful-fs';
import path from 'path';
import * as prettier from 'prettier';
import util from 'util';

import { FILE_TYPE } from '../shared/file-type.model';

gfs.gracefulify(fs);

const readfileFromFS = util.promisify(fs.readFile);
const writeFileToFS = util.promisify(fs.writeFile);

const fileComment = '/* 🤖 this file was generated by svg-to-ts */\n';

export const extractSvgContent = async (filePath: string): Promise<string> => {
  const fileContentRaw = await readfileFromFS(filePath, 'utf-8');
  return fileContentRaw.replace(/\r?\n|\r/g, ' ');
};

export async function writeFile(
  outputDirectory: string,
  fileName: string,
  fileContent: string,
  fileType = FILE_TYPE.TS,
): Promise<void> {
  const outputFile = path.join(outputDirectory, `${fileName}.${fileType}`);
  const formattedFileContent =
    fileType === FILE_TYPE.TS
      ? await formatContent(`${fileComment}${fileContent}`, outputFile)
      : `${fileComment}${fileContent}`;
  if (!fs.existsSync(outputDirectory)) {
    fs.mkdirSync(outputDirectory, { recursive: true });
  }
  await writeFileToFS(outputFile, formattedFileContent);
}

export const readFile = async (filePath: string): Promise<string> => {
  return readfileFromFS(filePath, 'utf-8');
};

export const deleteFolder = async (directoryPath: string) => {
  if (fs.existsSync(directoryPath)) {
    fs.readdirSync(directoryPath).forEach((filePath: string) => {
      const curPath = directoryPath + '/' + filePath;
      if (fs.lstatSync(curPath).isDirectory()) {
        deleteFolder(curPath);
      } else {
        fs.unlinkSync(curPath);
      }
    });
    fs.rmdirSync(directoryPath);
  }
};

export const deleteFiles = (filePaths: string[]): void => {
  filePaths.forEach((filePath: string) => fs.unlinkSync(filePath));
};

const formatContent = async (fileContent: string, filePath: string) => {
  // get the existing prettier config if it exists
  const existingPrettierConfig = await prettier.resolveConfig(filePath);
  // if there is no existing prettier config, use our default config
  const defaultPrettierConfig: prettier.Options = { singleQuote: true };
  const prettierConfig = existingPrettierConfig ?? defaultPrettierConfig;
  // ensure even if there is a parser set in the existing config we still use the typescript parser
  prettierConfig.parser = 'typescript';
  // use the existing prettier config along with the defaults to format the file content
  return await prettier.format(fileContent, prettierConfig);
};
